name: test_repo
version: "1.0.0"
config-version: 2

profile: test_repo

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_repo:
    staging:
      +materialized: view
    marts:
      +materialized: table
