
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
snowflake-it:
  outputs:
    local_dev:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it_dev # or switch to your local dev db
      warehouse: ddl_deployment_dbm_wh_dev
      schema: public
      threads: 4
      client_session_keep_alive: False

    dev:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it_dev
      warehouse: ddl_deployment_dbm_wh_dev
      schema: public
      threads: 4
      client_session_keep_alive: False

    dev_large:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it_dev
      warehouse: ddl_deployment_dbm_large_wh_dev
      schema: public
      threads: 4
      client_session_keep_alive: False

    staging:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it_dbt_test
      warehouse: ddl_deployment_dbm_wh_dev
      schema: public
      threads: 4
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it
      warehouse: ddl_deployment_dbm_wh
      schema: public
      threads: 8
      client_session_keep_alive: False

    prod_ci:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_cicd_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      role: ddl_deployment_role
      database: procore_it
      warehouse: ddl_deployment_dbm_wh_pr
      schema: public
      threads: 16
      client_session_keep_alive: False

    prod_large:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"

      role: ddl_deployment_role
      database: procore_it
      warehouse: ddl_deployment_dbm_large_wh
      schema: public
      threads: 8
      client_session_keep_alive: False

    pullrequest:
      type: snowflake
      account: procoreit

      #User/password auth
      user: ddl_deployment_user
      private_key: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('DBT_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
      role: ddl_deployment_role
      database: "{{ env_var('DBT_PR_DBNAME') }}"
      warehouse: ddl_deployment_dbm_large_wh_pr
      schema: public
      threads: 16
      client_session_keep_alive: False
  target: dev